export const MOCK_PLACES = [
  {
    id: "mp-001",
    name: "משרד רואי חשבון לוי ושות'",
    profession: "רואה חשבון",
    category: "חשבונאות",
    subcategory: "מס הכנסה",
    phone: "052-3301122",
    city: "תל אביב",
    address: "רחוב דיזנגוף 84, תל אביב",
    rating: 4.7,
    reviewCount: 134,
    isVerifiedPartner: false,
    source: "places_mock",
  },
  {
    id: "mp-002",
    name: "עו\"ד רחל שפירא",
    profession: "עורך דין",
    category: "משפטי",
    subcategory: "דיני חברות",
    phone: "054-9887766",
    city: "ירושלים",
    address: "רחוב יפו 45, ירושלים",
    rating: 4.5,
    reviewCount: 88,
    isVerifiedPartner: false,
    source: "places_mock",
  },
  {
    id: "mp-003",
    name: "סטודיו גרפי — נועם ברקוביץ",
    profession: "מעצב גרפי",
    category: "עיצוב",
    subcategory: "מיתוג",
    phone: "050-7712233",
    city: "הרצליה",
    address: "רחוב סוקולוב 17, הרצליה",
    rating: 4.8,
    reviewCount: 61,
    isVerifiedPartner: false,
    source: "places_mock",
  },
  {
    id: "mp-004",
    name: "ניר כהן — ייעוץ עסקי",
    profession: "יועץ עסקי",
    category: "ייעוץ",
    subcategory: "אסטרטגיה",
    phone: "053-4456789",
    city: "רעננה",
    address: "רחוב אחוזה 103, רעננה",
    rating: 4.3,
    reviewCount: 47,
    isVerifiedPartner: false,
    source: "places_mock",
  },
  {
    id: "mp-005",
    name: "דב טכנולוגיות — פיתוח תוכנה",
    profession: "מתכנת",
    category: "טכנולוגיה",
    subcategory: "פיתוח אפליקציות",
    phone: "058-1122334",
    city: "תל אביב",
    address: "רחוב הברזל 30, תל אביב",
    rating: 4.6,
    reviewCount: 29,
    isVerifiedPartner: false,
    source: "places_mock",
  },
  {
    id: "mp-006",
    name: "Maya Digital — שיווק דיגיטלי",
    profession: "שיווק דיגיטלי",
    category: "שיווק",
    subcategory: "רשתות חברתיות",
    phone: "052-8899001",
    city: "תל אביב",
    address: "רחוב ויצמן 12, תל אביב",
    rating: 4.4,
    reviewCount: 76,
    isVerifiedPartner: false,
    source: "places_mock",
  },
  {
    id: "mp-007",
    name: "סוכנות ביטוח — אורן פרידמן",
    profession: "סוכן ביטוח",
    category: "ביטוח",
    subcategory: "ביטוח עסקי",
    phone: "054-3344556",
    city: "ירושלים",
    address: "רחוב בן יהודה 22, ירושלים",
    rating: 4.2,
    reviewCount: 53,
    isVerifiedPartner: false,
    source: "places_mock",
  },
  {
    id: "mp-008",
    name: "מירב גולן — ניהול ספרים",
    profession: "מנהלת ספרים",
    category: "ניהול ספרים",
    subcategory: "הנהלת חשבונות",
    phone: "050-6677889",
    city: "רעננה",
    address: "רחוב עמל 5, רעננה",
    rating: 4.9,
    reviewCount: 112,
    isVerifiedPartner: false,
    source: "places_mock",
  },
  {
    id: "mp-009",
    name: "משרד עו\"ד אהרון בן-דוד",
    profession: "עורך דין",
    category: "משפטי",
    subcategory: "נדל\"ן",
    phone: "052-5566778",
    city: "הרצליה",
    address: "רחוב קוגל 8, הרצליה פיתוח",
    rating: 4.1,
    reviewCount: 38,
    isVerifiedPartner: false,
    source: "places_mock",
  },
  {
    id: "mp-010",
    name: "טל עמית — יועץ שיווק",
    profession: "שיווק דיגיטלי",
    category: "שיווק",
    subcategory: "קידום ממומן",
    phone: "053-9900112",
    city: "תל אביב",
    address: "שד' רוטשילד 55, תל אביב",
    rating: 4.5,
    reviewCount: 91,
    isVerifiedPartner: false,
    source: "places_mock",
  },
  {
    id: "mp-011",
    name: "עמית ביטוח ופיננסים",
    profession: "סוכן ביטוח",
    category: "ביטוח",
    subcategory: "ביטוח חיים",
    phone: "058-7788990",
    city: "תל אביב",
    address: "רחוב אבן גבירול 91, תל אביב",
    rating: 4.0,
    reviewCount: 24,
    isVerifiedPartner: false,
    source: "places_mock",
  },
  {
    id: "mp-012",
    name: "גיא הראל — רואה חשבון",
    profession: "רואה חשבון",
    category: "חשבונאות",
    subcategory: "מע\"מ ועוסק פטור",
    phone: "054-1122334",
    city: "ירושלים",
    address: "רחוב גרשון אגרון 2, ירושלים",
    rating: 4.6,
    reviewCount: 67,
    isVerifiedPartner: false,
    source: "places_mock",
  },
];

export const SUBCATEGORIES = {
  חשבונאות: ["מס הכנסה", "מע\"מ ועוסק פטור", "דוחות שנתיים"],
  משפטי: ["דיני חברות", "נדל\"ן", "חוזים"],
  עיצוב: ["מיתוג", "עיצוב אתרים", "עיצוב פרינט"],
  ייעוץ: ["אסטרטגיה", "גיוס הון", "ניהול"],
  טכנולוגיה: ["פיתוח אפליקציות", "אתרים", "אוטומציות"],
  שיווק: ["רשתות חברתיות", "קידום ממומן", "תוכן"],
  ביטוח: ["ביטוח עסקי", "ביטוח חיים", "ביטוח בריאות"],
  "ניהול ספרים": ["הנהלת חשבונות", "שכר ומשאבי אנוש", "דוחות חודשיים"],
};

export const CATEGORIES = Object.keys(SUBCATEGORIES);